### ISSUE TITLE
No se muestra opción de pago prestashop 1.7

### ISSUE THREAD

**Issue by SrRoland** [ComerciaGP/prestashop#11]
## Descripción del problema:
No aparece la opción de pago mediante Addon Payments en Prestashop 1.7

## Pasos seguidos para llegar al error

1. Se integra módulo para Prestashop 1.7 desde github
2. Se configura
3. Se intenta prueba de compra sin éxito.

**Comment by ecomm360** [comment]
Solved: en este caso el módulo que había instalado no era el correcto.
