### ISSUE TITLE
Error en los pedidos 

### ISSUE THREAD

**Issue by sgasconaddonpayments** [ComerciaGP/prestashop#4]
Al realizar una compra reciben el pago pero en la web no se ve el pedido y al cliente le da un error al haber realizado el pago.
Adjunto logs del servidor:

[Thu Nov 02 15:02:03.599800 2017] [:error] [pid 29070] [client 83.173.141.241:50821] PHP Warning: array_key_exists() expects parameter 2 to be array, null given in /server/www/html/gaimo.com/httpdocs/tienda/modules/mailchimpintegration/mailchimpintegration.php on line 498, referer: http://www.gaimo.com/tienda/oi18/288-invierno-2018-1155.html
[Thu Nov 02 15:02:03.607596 2017] [:error] [pid 29070] [client 83.173.141.241:50821] PHP Warning: array_key_exists() expects parameter 2 to be array, null given in /server/www/html/gaimo.com/httpdocs/tienda/modules/mailchimpintegration/mailchimpintegration.php on line 498, referer: http://www.gaimo.com/tienda/oi18/288-invierno-2018-1155.html
[Thu Nov 02 15:02:05.874964 2017] [:error] [pid 28815] [client 83.173.141.241:50822] PHP Warning: array_key_exists() expects parameter 2 to be array, null given in /server/www/html/gaimo.com/httpdocs/tienda/modules/mailchimpintegration/mailchimpintegration.php on line 498, referer: http://www.gaimo.com/tienda/oi18/288-invierno-2018-1155.html

**Comment by sgasconaddonpayments** [comment]
Buenos días,
Comercio nos indica que el error aun no esta solucionado. ¿Se podría revisar este caso?

**Comment by ecomm360** [comment]
Hola @sgasconaddonpayments,

hemos revisado el motivo del error que nos presentas. **Es un error ajeno al módulo de este repositorio** al menos en la pruebas que hemos llevado a cabo.

El módulo que está provocando los warnings es modules /mailchimpintegration. Realiza  una prueba desactivando el mismo déjanos el log de los mensajes de error que se muestran.

Gracias.
