### ISSUE TITLE
Prestashop 1.7.2.2

### ISSUE THREAD

**Issue by sgasconaddonpayments** [ComerciaGP/prestashop#5]
El pluguin no funciona correctamente en la version 1.7.2.2. Nos indican que el modulo en si no se muestra en la plataforma en el proceso de pago

**Comment by ecomm360** [comment]
Hola @sgasconaddonpayments 

hemos realizado una prueba en una versión 1.7.2.2 limpia; 

nos aparecer el módulo dentro de los métodos de pago a seleccionar en el carrito, además hemos realizado un pedido de prueba que ha funcionado correctamente.

![captura de pantalla 2017-11-20 a las 10 59 34](https://user-images.githubusercontent.com/12048727/33012867-7574078e-cde2-11e7-9053-0ace7a3fa339.png)

Para tratar de ayudar al cliente, por favor que revise en las opciones de pago, que el módulo de Addonpayments esté activo para el país concreto además de tener seleccionado el mismo en relación a los transportistas (en Pagos -> Preferencias).

![captura de pantalla 2017-11-20 a las 11 02 55](https://user-images.githubusercontent.com/12048727/33012890-7cbce704-cde2-11e7-8553-0187353147d4.png)

Quedamos a la espera de más novedades.
